repos:
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 2.3.351
    hooks:
      - id: checkov
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-xml
      - id: end-of-file-fixer
      - id: detect-aws-credentials
        args: [ --allow-missing-credentials]
      - id: detect-private-key
      - id: trailing-whitespace
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.0
    hooks:
      - id: terraform_fmt
